url <- Sys.getenv("ACTIONS_ID_TOKEN_REQUEST_URL")
token <- Sys.getenv("ACTIONS_ID_TOKEN_REQUEST_TOKEN")

r <- httr2::request(url)
print(r)
r <- r |> httr2::req_url_query(audience="xxxx") |> httr2::req_auth_bearer_token(token)
print(r)
r <- r |> httr2::req_perform()
print(r)
print(r |> httr2::resp_body_json())
