on: push
jobs:
  test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: packit
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: |
            https://mrc-ide.r-universe.dev
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            github::mrc-ide/orderly2@service-token

      - run: Rscript --verbose run.R
